In [28]:
train_values <- read.csv("train_values.csv",stringsAsFactors = T)
test_values <- read.csv("test_values.csv",stringsAsFactors = T)
train_labels <- read.csv("train_labels.csv",stringsAsFactors = T)
submission_format <- read.csv("submission_format.csv",stringsAsFactors = T)
data <- merge(train_values,train_labels,by=c('building_id','building_id'),all.x=T)
test <- test_values

# Data Pre-procesing

On dispose d'information sur les variable que l'ordinateur lui na pas. 
On vas essayer de lui les transmettre.

## Discution des package uttiliser

In [ ]:
#install.packages("ggplot2")
#install.packages("lattice")
#install.packages("caret")
#install.packages("dplyr")

In [5]:
library(ggplot2)
library(lattice)
library(caret)
library(dplyr)
library(tictoc)

## Pertinance des variable et de leur type

#### damage_grade

Les variable damage_grade que l'on cherche a predire prenne 3 valeur possible sous forme d'entier 1,2,3.
En se sens, il s'agit de variables catégoriques plutôt que de variable numérique. 
En effet, si on avait remplacer damage_grade 3 par damage_grade 10 on aurait pas changer l'information a notre disposition. 
Alors que l'ordinateur traiterait ses information différament. 
Cependnant, puisqu'il existe une structure d'ordre au sens de cette variable (i.e 1 < 2 < 3) cella peux quand même faire du sens de les traitrer comme des variable numérique. 
On pourait evisagabler de changer leur valeur tous en preservant l'odre interne comme un parametre de tunings.

#### building_id 

la variable building_id est un identifiant unique et aléatoir et ne contien pas d'information uttile pour notre problème.

#### geo_level 

désigne les region géographic dans les quelle le batiment se situe.
Les 3 variable on une strucutre interne qui ne sont pas retranscrite dans le data set (i.e geo_level_3 inclu geo_level_2 inclue geo_level_1)
De plus, il s'agit d'entier qui n'apporte pas en temps que telle d'information. 
Si l'on echange les les indice des zone 1 et 1200 dans geo_level_3, cella ne change pas l'information a la quelle on dispose mais changera nos algorithme. 
On ne devrait pas les traiter comme variable numérique mais plutôt comme variable catégorique. 
Cependant, en pratique, elle prene un trop grand nombre de valeur différente que pour pouvoir s'en servir commme variable catégorique. 
Intuitivement, il s'aggit de variable important elle devrait donc porter une iformation importante.

#### variable catégorique 

L'information des autre varibale catégorique nous étant cacher, on se sera pas en messur d'en tirer plus d'inforamtion.

In [58]:
length(unique(data$geo_level_3_id))

[1] 11595

In [59]:
length(unique(data$geo_level_2_id))

[1] 1414

In [60]:
length(unique(data$geo_level_1_id))

[1] 31

In [29]:
mean_damage_level_1 <- 0:30
mean_damage_level_2 <- 0:1427
mean_damage_level_3 <- 0:12567

sd_damage_level_1 <- 0:30
sd_damage_level_2 <- 0:1427
sd_damage_level_3 <- 0:12567


mean_level_1 <- data %>% group_by(geo_level_1_id) %>% 
  summarise(mean_damage=mean(damage_grade),
            .groups = 'drop')

mean_level_2 <- data %>% group_by(geo_level_2_id) %>% 
  summarise(mean_damage=mean(damage_grade),
            .groups = 'drop')

mean_level_3 <- data %>% group_by(geo_level_3_id) %>% 
  summarise(mean_damage=mean(damage_grade),
            .groups = 'drop')

sd_level_1 <- data %>% group_by(geo_level_1_id) %>% 
  summarise(sd_damage=sd(damage_grade),
            .groups = 'drop')

sd_level_2 <- data %>% group_by(geo_level_2_id) %>% 
  summarise(sd_damage=sd(damage_grade),
            .groups = 'drop')

sd_level_3 <- data %>% group_by(geo_level_3_id) %>% 
  summarise(sd_damage=sd(damage_grade),
            .groups = 'drop')


for (i in 1:31){mean_damage_level_1[i] <- mean_level_1[i,2]}  

k <- 1
for (i in 1:1428){if(i-1 == mean_level_2[k,1]){ 
        mean_damage_level_2[i] <- mean_level_2[k,2]
        k <- k+1 } else { mean_damage_level_2[i] <- NA}}

k <- 1
for (i in 1:12568){if(i-1 == mean_level_3[k,1]){ 
        mean_damage_level_3[i] <- mean_level_3[k,2]
        k <- k+1 } else { mean_damage_level_3[i] <- NA}}


for (i in 1:31){sd_damage_level_1[i] <- sd_level_1[i,2]}  

k <- 1
for (i in 1:1428){if(i-1 == sd_level_2[k,1]){ 
        sd_damage_level_2[i] <- sd_level_2[k,2]
        k <- k+1 } else { sd_damage_level_2[i] <- NA}}

k <- 1
for (i in 1:12568){if(i-1 == sd_level_3[k,1]){ 
        sd_damage_level_3[i] <- sd_level_3[k,2]
        k <- k+1 } else { sd_damage_level_3[i] <- NA}}

In [ ]:
for (i in 1:nrow(data)){
    if(is.na(mean_damage_level_3[data[i,c("geo_level_3_id")]+1])){
        if(is.na(mean_damage_level_2[data[i,c("geo_level_2_id")]+1])){
            data$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))
        } else {data$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
    } else {data$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_3[data[i,c("geo_level_3_id")]+1]))
            data$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[data[i,c("geo_level_2_id")]+1]))
            data$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
}

for (i in 1:nrow(data)){
    if(is.na(sd_damage_level_3[data[i,c("geo_level_3_id")]+1])){
        if(is.na(sd_damage_level_2[data[i,c("geo_level_2_id")]+1])){
            data$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))
            data$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))
        } else {data$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[data[i,c("geo_level_2_id")]+1]))
                data$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
    } else {data$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_3[data[i,c("geo_level_3_id")]+1]))
            data$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[data[i,c("geo_level_2_id")]+1]))
            data$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[data[i,c("geo_level_1_id")]+1]))}
}

In [38]:
for (i in 1:nrow(test)){
    if(is.na(mean_damage_level_3[test[i,c("geo_level_3_id")]+1])){
        if(is.na(mean_damage_level_2[test[i,c("geo_level_2_id")]+1])){
            test$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))
        } else {test$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
    } else {test$geo_level_3_mean_damage[i] <- as.numeric(unlist(mean_damage_level_3[test[i,c("geo_level_3_id")]+1]))
            test$geo_level_2_mean_damage[i] <- as.numeric(unlist(mean_damage_level_2[test[i,c("geo_level_2_id")]+1]))
            test$geo_level_1_mean_damage[i] <- as.numeric(unlist(mean_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
}

for (i in 1:nrow(test)){
    if(is.na(sd_damage_level_3[test[i,c("geo_level_3_id")]+1])){
        if(is.na(sd_damage_level_2[test[i,c("geo_level_2_id")]+1])){
            test$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))
            test$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))
        } else {test$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[test[i,c("geo_level_2_id")]+1]))
                test$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
    } else {test$geo_level_3_sd_damage[i] <- as.numeric(unlist(sd_damage_level_3[test[i,c("geo_level_3_id")]+1]))
            test$geo_level_2_sd_damage[i] <- as.numeric(unlist(sd_damage_level_2[test[i,c("geo_level_2_id")]+1]))
            test$geo_level_1_sd_damage[i] <- as.numeric(unlist(sd_damage_level_1[test[i,c("geo_level_1_id")]+1]))}
}

In [185]:
data <- data[,-c(1,2,3,4)]
test <- test[,-c(1,2,3,4)]

In [43]:
data[1:3,]

  building_id geo_level_1_id geo_level_2_id geo_level_3_id count_floors_pre_eq
1  4          30             266             1224          1
2  8          17             409            12182          2
3 12          17             716             7056          2
  age area_percentage height_percentage land_surface_condition foundation_type
1 25   5              2                 t                      r
2  0  13              7                 t                      r
3  5  12              6                 o                      r
  ⋯ has_secondary_use_gov_office has_secondary_use_use_police
1 ⋯ 0                            0
2 ⋯ 0                            0
3 ⋯ 0                            0
  has_secondary_use_other damage_grade geo_level_3_mean_damage
1 0                       2            1.971429
2 0                       3            3.000000
3 0                       3            3.000000
  geo_level_2_mean_damage geo_level_1_mean_damage geo_level_3_sd_damage
1 1.984293                2.020477                0.1690309
2 2.977444                2.794480                0.0000000
3 2.984772                2.794480                0.0000000
  geo_level_2_sd_damage geo_level_1_sd_damage
1 0.2987067             0.4558226
2 0.1490457             0.4352255
3 0.1227723             0.4352255

In [45]:
data <- data %>% relocate(geo_level_1_mean_damage,.after=geo_level_1_id) %>% 
relocate(geo_level_2_mean_damage,.after=geo_level_2_id) %>% 
relocate(geo_level_3_mean_damage,.after=geo_level_3_id) %>% 
relocate(geo_level_1_sd_damage,.after=geo_level_1_mean_damage) %>%
relocate(geo_level_2_sd_damage,.after=geo_level_2_mean_damage) %>% 
relocate(geo_level_3_sd_damage,.after=geo_level_3_mean_damage)

In [ ]:
test <- test %>% relocate(geo_level_1_mean_damage,.after=geo_level_1_id) %>% 
relocate(geo_level_2_mean_damage,.after=geo_level_2_id) %>% 
relocate(geo_level_3_mean_damage,.after=geo_level_3_id) %>% 
relocate(geo_level_1_sd_damage,.after=geo_level_1_mean_damage) %>%
relocate(geo_level_2_sd_damage,.after=geo_level_2_mean_damage) %>% 
relocate(geo_level_3_sd_damage,.after=geo_level_3_mean_damage)

In [47]:
write.csv(data, file = "data_target_encoding.csv", row.names = FALSE)

In [182]:
#data[c("damage_grade")] <- lapply(data[c("damage_grade")], function(x) as.factor(x))
nzv <- nearZeroVar(data)
data <- data[, -nzv]
test <- test[, -nzv]

In [173]:
dim(data)

[1] 260601     21

In [174]:
data[1:2,]

  count_floors_pre_eq age area_percentage height_percentage
1 1                   25   5              2
2 2                    0  13              7
  land_surface_condition foundation_type roof_type ground_floor_type
1 t                      r               n         f
2 t                      r               n         f
  other_floor_type position ⋯ has_superstructure_mud_mortar_stone
1 j                s        ⋯ 1
2 q                s        ⋯ 1
  has_superstructure_mud_mortar_brick has_superstructure_cement_mortar_brick
1 0                                   0
2 0                                   0
  has_superstructure_timber has_superstructure_bamboo count_families
1 0                         0                         0
2 0                         0                         1
  has_secondary_use has_secondary_use_agriculture damage_grade geo_level_damage
1 0                 0                             2            1.971429
2 0                 0                             3            3.000000

In [186]:
dummy_data <- dummyVars(" ~ .", data=data)  
data_dummy <- data.frame(predict(dummy_data, newdata = data))

In [187]:
cor(data_dummy)

                                       count_floors_pre_eq age
count_floors_pre_eq                     1.000000000         8.666803e-02
age                                     0.086668031         1.000000e+00
area_percentage                         0.101071177        -4.322511e-03
height_percentage                       0.772734385         6.107355e-02
land_surface_condition.n               -0.038525062        -1.208668e-02
land_surface_condition.o               -0.023155769        -1.563694e-02
land_surface_condition.t                0.046218344         1.843401e-02
foundation_type.h                      -0.040922485        -4.959536e-03
foundation_type.i                       0.040634019        -4.885999e-02
foundation_type.r                       0.131691925         7.263971e-02
foundation_type.u                      -0.095874163        -2.013095e-02
foundation_type.w                      -0.133956351        -5.118399e-02
roof_type.n                            -0.099278162         2.250417e-02
roof_type.q                             0.085248635        -1.465003e-03
roof_type.x                             0.038167098        -4.008712e-02
ground_floor_type.f                     0.057356319         4.366778e-02
ground_floor_type.m                    -0.004770235        -3.588865e-03
ground_floor_type.v                    -0.070247038        -5.234195e-02
ground_floor_type.x                     0.001164259        -6.342776e-03
ground_floor_type.z                    -0.037900868         2.427564e-05
other_floor_type.j                     -0.658161110        -5.163363e-02
other_floor_type.q                      0.353822847         5.461508e-02
other_floor_type.s                      0.172380070        -3.104470e-02
other_floor_type.x                      0.081221899        -3.244466e-03
position.j                              0.246396152         5.634776e-02
position.o                              0.219763706         6.949224e-02
position.s                             -0.229465245        -4.969624e-02
position.t                              0.056249239         4.849855e-03
has_superstructure_adobe_mud            0.174851702         6.803247e-02
has_superstructure_mud_mortar_stone    -0.027115976         1.321263e-03
has_superstructure_mud_mortar_brick     0.257278702         7.952544e-02
has_superstructure_cement_mortar_brick -0.085820914        -3.699192e-02
has_superstructure_timber              -0.056637092         5.855425e-03
has_superstructure_bamboo              -0.070487236        -8.374469e-03
count_families                          0.086585990         5.309281e-03
has_secondary_use                       0.052125461        -8.787676e-03
has_secondary_use_agriculture          -0.005293656        -2.194027e-03
damage_grade                            0.122308494         2.927330e-02
geo_level_damage                        0.168440126        -2.786670e-03
                                       area_percentage height_percentage
count_floors_pre_eq                     0.1010711767    0.7727343845
age                                    -0.0043225113    0.0610735493
area_percentage                         1.0000000000    0.1966452848
height_percentage                       0.1966452848    1.0000000000
land_surface_condition.n               -0.0284224314   -0.0199774726
land_surface_condition.o                0.0005412602   -0.0125886951
land_surface_condition.t                0.0258172259    0.0242399106
foundation_type.h                      -0.0089222331   -0.0274728807
foundation_type.i                       0.3016877206    0.1632006631
foundation_type.r                      -0.1985058610    0.0086609521
foundation_type.u                       0.1268601156   -0.0367277949
foundation_type.w                      -0.0648491875   -0.1068521482
roof_type.n                            -0.1487601691   -0.1261401189
roof_type.q                            -0.0430298004    0.0394799596
roof_type.x                             0.3577768628    0.1696571776
ground_floor_type.f                    -0.2582591222   -0.0525020252
ground_floor_type.m                     0.0095832440    0.0004236663
ground_floor_type.v                     0.3281504056    0.0620006228
ground_floor_type.x                     0.0208474971    0.0142286838
ground_floor_type.z                    -0.0005376301   -0.0241870097
other_floor_type.j                     -0.0375121061   -0.5313584696
other_floor_type.q                     -0.1295567279    0.2027265278
other_floor_type.s                      0.3178572474    0.3058736509
other_floor_type.x                      0.0247022478    0.0788910609
position.j                              0.0704915991    0.2290069588
position.o                             -0.0101388259    0.1575603330
position.s                             -0.0472995402   -0.2161066777
position.t                              0.0139915109    0.0673310703
has_superstructure_adobe_mud            0.0262867471    0.1497251704
has_superstructure_mud_mortar_stone    -0.2255405528   -0.1065729891
has_superstructure_mud_mortar_brick     0.0533615320    0.2090977687
has_superstructure_cement_mortar_brick  0.2108003595    0.0016977509
has_superstructure_timber              -0.0539651165   -0.0524024758
has_superstructure_bamboo              -0.0316412341   -0.0633418824
count_families                          0.0886301872    0.0643160814
has_secondary_use                       0.1224006096    0.0917798914
has_secondary_use_agriculture          -0.0164775241   -0.0053900151
damage_grade                           -0.1252205157    0.0481300237
geo_level_damage                       -0.0780848143    0.1017125591
                                       land_surface_condition.n
count_floors_pre_eq                    -0.038525062
age                                    -0.012086677
area_percentage                        -0.028422431
height_percentage                      -0.019977473
land_surface_condition.n                1.000000000
land_surface_condition.o               -0.072133201
land_surface_condition.t               -0.883395457
foundation_type.h                      -0.004123188
foundation_type.i                      -0.028119945
foundation_type.r                       0.026637757
foundation_type.u                      -0.020409532
foundation_type.w                       0.003250465
roof_type.n                             0.043577087
roof_type.q                            -0.023711482
roof_type.x                            -0.040881050
ground_floor_type.f                     0.028089964
ground_floor_type.m                     0.005259228
ground_floor_type.v                    -0.050064449
ground_floor_type.x                     0.005384728
ground_floor_type.z                     0.027099510
other_floor_type.j                     -0.001641842
other_floor_type.q                     -0.018645601
other_floor_type.s                     -0.029515492
other_floor_type.x                      0.042294585
position.j                             -0.030546488
position.o                             -0.022564601
position.s                              0.024974137
position.t                             -0.004253791
has_superstructure_adobe_mud           -0.005326544
has_superstructure_mud_mortar_stone     0.074832008
has_superstructure_mud_mortar_brick    -0.050381906
has_superstructure_cement_mortar_brick -0.054304164
has_superstructure_timber               0.034529749
has_superstructure_bamboo               0.022884006
count_families                         -0.008839824
has_secondary_use                      -0.005813440
has_secondary_use_agriculture           0.005457553
damage_grade                            0.008529759
geo_level_damage                        0.008013137
                                       land_surface_condition.o
count_floors_pre_eq                    -0.0231557691
age                                    -0.0156369399
area_percentage                         0.0005412602
height_percentage                      -0.0125886951
land_surface_condition.n               -0.0721332011
land_surface_condition.o                1.0000000000
land_surface_condition.t               -0.4036853666
foundation_type.h                      -0.0032915220
foundation_type.i                      -0.0054854365
foundation_type.r                      -0.0022533602
foundation_type.u                      -0.0144038105
foundation_type.w                       0.0232149091
roof_type.n                             0.0153813874
roof_type.q                            -0.0070894426
roof_type.x                            -0.0166828138
ground_floor_type.f                     0.0062124482
ground_floor_type.m                    -0.0025791350
ground_floor_type.v                    -0.0232839821
ground_floor_type.x                     0.0146479624
ground_floor_type.z                     0.0024533501
other_floor_type.j                      0.0014909002
other_floor_type.q                     -0.0084442081
other_floor_type.s                     -0.0064328681
other_floor_type.x                      0.0130934863
position.j                             -0.0169590708
position.o                             -0.0126200923
position.s                              0.0175348829
position.t                             -0.0064672902
has_superstructure_adobe_mud           -0.0196001755
has_superstructure_mud_mortar_stone     0.0234135958
has_superstructure_mud_mortar_brick    -0.0356724205
has_superstructure_cement_mortar_brick -0.0212618077
has_superstructure_timber               0.0288783987
has_superstructure_bamboo               0.0209044520
count_families                         -0.0007053341
has_secondary_use                       0.0078684842
has_secondary_use_agriculture           0.0032586222
damage_grade                            0.0150776540
geo_level_damage                        0.0183822792
                                       land_surface_condition.t
count_floors_pre_eq                     0.0462183437
age                                     0.0184340079
area_percentage                         0.0258172259
height_percentage                       0.0242399106
land_surface_condition.n               -0.8833954570
land_surface_condition.o               -0.4036853666
land_surface_condition.t                1.0000000000
foundation_type.h                       0.0053286771
foundation_type.i                       0.0283714161
foundation_type.r                      -0.0233757330
foundation_type.u                       0.0254890693
foundation_type.w                      -0.0138891880
roof_type.n                            -0.0471996922
roof_type.q                             0.0250812342
roof_type.x                             0.0453381294
ground_floor_type.f                    -0.0286855026
ground_floor_type.m                    -0.0036124113
ground_floor_type.v                     0.0568635193
ground_floor_type.x                    -0.0118217209
ground_floor_type.z                    -0.0260107514
other_floor_type.j                      0.0008055381
other_floor_type.q                      0.0210709055
other_floor_type.s                      0.0300966867
other_floor_type.x                     -0.0449482936
position.j                              0.0359881662
position.o                              0.0266278033
position.s                             -0.0311472654
position.t                              0.0069406197
has_superstructure_adobe_mud            0.0140951585
has_superstructure_mud_mortar_stone    -0.0796433887
has_superstructure_mud_mortar_brick     0.0629754548
has_superstructure_cement_mortar_brick  0.0598024340
has_superstructure_timber              -0.0452422845
has_superstructure_bamboo              -0.0308132143
count_families                          0.0084400621
has_secondary_use                       0.0016355700
has_secondary_use_agriculture          -0.0065372153
damage_grade                           -0.0149085101
geo_level_damage                       -0.0159873051
                                       foundation_type.h foundation_type.i
count_floors_pre_eq                    -0.0409224848      0.040634019
age                                    -0.0049595365     -0.048859993
area_percentage                        -0.0089222331      0.301687721
height_percentage                      -0.0274728807      0.163200663
land_surface_condition.n               -0.0041231877     -0.028119945
land_surface_condition.o               -0.0032915220     -0.005485437
land_surface_condition.t                0.0053286771      0.028371416
foundation_type.h                       1.0000000000     -0.015375858
foundation_type.i                      -0.0153758579      1.000000000
foundation_type.r                      -0.1719871811     -0.473285407
foundation_type.u                      -0.0179844671     -0.049490815
foundation_type.w                      -0.0185499447     -0.051046933
roof_type.n                            -0.0004446276     -0.278240524
roof_type.q                             0.0071527618     -0.108693998
roof_type.x                            -0.0117473597      0.718842174
ground_floor_type.f                    -0.0132377612     -0.406708434
ground_floor_type.m                     0.0282960806      0.002370738
ground_floor_type.v                    -0.0008207893      0.586806484
ground_floor_type.x                     0.0013656644     -0.033341444
ground_floor_type.z                     0.0620147144     -0.008398185
other_floor_type.j                      0.0445558241      0.082858909
other_floor_type.q                     -0.0650976082     -0.264690429
other_floor_type.s                     -0.0080777475      0.617344888
other_floor_type.x                      0.0456472639     -0.085489141
position.j                              0.0155385910      0.123051789
position.o                             -0.0049122093      0.009349762
position.s                             -0.0114919201     -0.119468163
position.t                              0.0049632928      0.059076154
has_superstructure_adobe_mud            0.0179154586     -0.061758634
has_superstructure_mud_mortar_stone    -0.1073031124     -0.359322680
has_superstructure_mud_mortar_brick    -0.0105876869     -0.043979123
has_superstructure_cement_mortar_brick  0.0052853266      0.246290004
has_superstructure_timber               0.0475863740     -0.109811913
has_superstructure_bamboo               0.0103474425     -0.059701535
count_families                         -0.0010805502     -0.026917346
has_secondary_use                       0.0031112382      0.167006323
has_secondary_use_agriculture           0.0028985657     -0.043895800
damage_grade                           -0.0162017492     -0.263900995
geo_level_damage                       -0.0102078346     -0.140997635
                                       foundation_type.r ⋯
count_floors_pre_eq                     0.131691925      ⋯
age                                     0.072639710      ⋯
area_percentage                        -0.198505861      ⋯
height_percentage                       0.008660952      ⋯
land_surface_condition.n                0.026637757      ⋯
land_surface_condition.o               -0.002253360      ⋯
land_surface_condition.t               -0.023375733      ⋯
foundation_type.h                      -0.171987181      ⋯
foundation_type.i                      -0.473285407      ⋯
foundation_type.r                       1.000000000      ⋯
foundation_type.u                      -0.553581197      ⋯
foundation_type.w                      -0.570987206      ⋯
roof_type.n                             0.260968541      ⋯
roof_type.q                            -0.006366217      ⋯
roof_type.x                            -0.483566431      ⋯
ground_floor_type.f                     0.385112150      ⋯
ground_floor_type.m                    -0.023390299      ⋯
ground_floor_type.v                    -0.514299786      ⋯
ground_floor_type.x                     0.005984312      ⋯
ground_floor_type.z                    -0.050744271      ⋯
other_floor_type.j                     -0.202061762      ⋯
other_floor_type.q                      0.325542358      ⋯
other_floor_type.s                     -0.415477154      ⋯
other_floor_type.x                      0.008311691      ⋯
position.j                             -0.067187583      ⋯
position.o                              0.004532642      ⋯
position.s                              0.038126794      ⋯
position.t                             -0.004205432      ⋯
has_superstructure_adobe_mud            0.098100560      ⋯
has_superstructure_mud_mortar_stone     0.538937022      ⋯
has_superstructure_mud_mortar_brick     0.071138734      ⋯
has_superstructure_cement_mortar_brick -0.405372425      ⋯
has_superstructure_timber              -0.126081927      ⋯
has_superstructure_bamboo              -0.136060826      ⋯
count_families                          0.034281016      ⋯
has_secondary_use                      -0.106780588      ⋯
has_secondary_use_agriculture           0.038260891      ⋯
damage_grade                            0.343355426      ⋯
geo_level_damage                        0.307699619      ⋯
                                       has_superstructure_mud_mortar_stone
count_floors_pre_eq                    -0.027115976
age                                     0.001321263
area_percentage                        -0.225540553
height_percentage                      -0.106572989
land_surface_condition.n                0.074832008
land_surface_condition.o                0.023413596
land_surface_condition.t               -0.079643389
foundation_type.h                      -0.107303112
foundation_type.i                      -0.359322680
foundation_type.r                       0.538937022
foundation_type.u                      -0.260836024
foundation_type.w                      -0.251561638
roof_type.n                             0.184909495
roof_type.q                             0.049611422
roof_type.x                            -0.437897659
ground_floor_type.f                     0.382413555
ground_floor_type.m                    -0.032286953
ground_floor_type.v                    -0.487755900
ground_floor_type.x                    -0.012591261
ground_floor_type.z                    -0.064280869
other_floor_type.j                     -0.206888966
other_floor_type.q                      0.325957015
other_floor_type.s                     -0.366995313
other_floor_type.x                     -0.014855294
position.j                             -0.225523390
position.o                             -0.143058707
position.s                              0.199138012
position.t                             -0.053986707
has_superstructure_adobe_mud           -0.306861168
has_superstructure_mud_mortar_stone     1.000000000
has_superstructure_mud_mortar_brick    -0.376207673
has_superstructure_cement_mortar_brick -0.470714995
has_superstructure_timber              -0.040176970
has_superstructure_bamboo              -0.054657208
count_families                          0.001575770
has_secondary_use                      -0.087519913
has_secondary_use_agriculture           0.058261234
damage_grade                            0.291325239
geo_level_damage                        0.280965609
                                       has_superstructure_mud_mortar_brick
count_floors_pre_eq                     0.2572787019
age                                     0.0795254426
area_percentage                         0.0533615320
height_percentage                       0.2090977687
land_surface_condition.n               -0.0503819064
land_surface_condition.o               -0.0356724205
land_surface_condition.t                0.0629754548
foundation_type.h                      -0.0105876869
foundation_type.i                      -0.0439791230
foundation_type.r                       0.0711387338
foundation_type.u                      -0.0166623856