In [1]:
library(MLmetrics)
library(randomForest)
library(dplyr) 

ConfusionMatrix <- function(y_pred, y_true) {
  Confusion_Mat <- table(y_true, y_pred)
  return(Confusion_Mat)
}
 
ConfusionDF <- function(y_pred, y_true) {
  Confusion_DF <- transform(as.data.frame(ConfusionMatrix(y_pred, y_true)),
                            y_true = as.character(y_true),
                            y_pred = as.character(y_pred),
                            Freq = as.integer(Freq))
  return(Confusion_DF)
}
 
Precision_micro <- function(y_true, y_pred, labels = NULL) {
  Confusion_DF <- ConfusionDF(y_pred, y_true)
 
  if (is.null(labels) == TRUE) labels <- unique(c(y_true, y_pred))
  # this is not bulletproof since there might be labels missing (in strange cases)
  # in strange cases where they existed in training set but are missing from test ground truth and predictions.
 
  TP <- c()
  FP <- c()
  for (i in c(1:length(labels))) {
    positive <- labels[i]
   
    # it may happen that a label is never predicted (missing from y_pred) but exists in y_true
    # in this case ConfusionDF will not have these lines and thus the simplified code crashes
    # TP[i] <- as.integer(Confusion_DF[which(Confusion_DF$y_true==positive & Confusion_DF$y_pred==positive), "Freq"])
    # FP[i] <- as.integer(sum(Confusion_DF[which(Confusion_DF$y_true!=positive & Confusion_DF$y_pred==positive), "Freq"]))
   
    # workaround:
    # i don't want to change ConfusionDF since i don't know if the current behaviour is a feature or a bug.
    tmp <- Confusion_DF[which(Confusion_DF$y_true==positive & Confusion_DF$y_pred==positive), "Freq"]
    TP[i] <- if (length(tmp)==0) 0 else as.integer(tmp)
   
    tmp <- Confusion_DF[which(Confusion_DF$y_true!=positive & Confusion_DF$y_pred==positive), "Freq"]
    FP[i] <- if (length(tmp)==0) 0 else as.integer(sum(tmp))
  }
  Precision_micro <- sum(TP) / (sum(TP) + sum(FP))
  return(Precision_micro)
}
 
Recall_micro <- function(y_true, y_pred, labels = NULL) {
  Confusion_DF <- ConfusionDF(y_pred, y_true)
 
  if (is.null(labels) == TRUE) labels <- unique(c(y_true, y_pred))
  # this is not bulletproof since there might be labels missing (in strange cases)
  # in strange cases where they existed in training set but are missing from test ground truth and predictions.
 
  TP <- c()
  FN <- c()
  for (i in c(1:length(labels))) {
    positive <- labels[i]
   
    # short version, comment out due to bug or feature of Confusion_DF
    # TP[i] <- as.integer(Confusion_DF[which(Confusion_DF$y_true==positive & Confusion_DF$y_pred==positive), "Freq"])
    # FP[i] <- as.integer(sum(Confusion_DF[which(Confusion_DF$y_true==positive & Confusion_DF$y_pred!=positive), "Freq"]))
   
    # workaround:
    tmp <- Confusion_DF[which(Confusion_DF$y_true==positive & Confusion_DF$y_pred==positive), "Freq"]
    TP[i] <- if (length(tmp)==0) 0 else as.integer(tmp)
 
    tmp <- Confusion_DF[which(Confusion_DF$y_true==positive & Confusion_DF$y_pred!=positive), "Freq"]
    FN[i] <- if (length(tmp)==0) 0 else as.integer(sum(tmp))
  }
  Recall_micro <- sum(TP) / (sum(TP) + sum(FN))
  return(Recall_micro)
}
 
F1_Score_micro <- function(y_true, y_pred, labels = NULL) {
  if (is.null(labels) == TRUE) labels <- unique(c(y_true, y_pred)) # possible problems if labels are missing from y_*
  Precision <- Precision_micro(y_true, y_pred, labels)
  Recall <- Recall_micro(y_true, y_pred, labels)
  F1_Score_micro <- 2 * (Precision * Recall) / (Precision + Recall)
  return(F1_Score_micro)
}

Warning message:
"le package 'MLmetrics' a été compilé avec la version R 4.2.3"

Attachement du package : 'MLmetrics'


L'objet suivant est masqué depuis 'package:base':

    Recall


Warning message:
"le package 'randomForest' a été compilé avec la version R 4.2.3"
randomForest 4.7-1.1

Type rfNews() to see new features/changes/bug fixes.

Warning message:
"le package 'dplyr' a été compilé avec la version R 4.2.3"

Attachement du package : 'dplyr'


L'objet suivant est masqué depuis 'package:randomForest':

    combine


Les objets suivants sont masqués depuis 'package:stats':

    filter, lag


Les objets suivants sont masqués depuis 'package:base':

    intersect, setdiff, setequal, union

In [2]:
datam<-read.csv("data_target_encoding.csv",stringsAsFactors = T)

In [3]:
set.seed(2)
k = 10

accuracy_vec <- array(0,k)

n_trees <- c(10,20,100)
nfeat <- ncol(datam)-1 #I remove 2 to remove building_id and damage_grade
m_tries <- c(floor(0.5*sqrt(nfeat)),floor(sqrt(nfeat)),floor(2*sqrt(nfeat)))
accuracy_vec <- data.frame(matrix(ncol = 4, nrow = 0))
colnames(accuracy_vec)<-c('fold','n_trees','mtry','F1')
nrows<-nrow(datam)
datam_idx <- sample(1:nrows)
split <- floor(nrows*0.8)
target_variable <- match('damage_grade', colnames(datam)) #we will remove id.
pb <- txtProgressBar(min = 0, max = length(n_trees), style = 3)

# 1. Shuffle the dataset randomly.
datam_idx <- sample(1:nrow(datam))

# 2. Split the dataset into k groups
max <- ceiling(nrow(datam)/k)
splits <- split(datam_idx, ceiling(seq_along(datam_idx)/max))

pb <- txtProgressBar(min = 0, max = k*length(n_trees)*length(m_tries), style = 3)
counter <-0

# 3. For each unique group:
for (i in 1:k){
    for (j in (n_trees)){
        for (l in m_tries){
            #3.1 Take the group as a hold out or test data set
            test_data <- datam[splits[[i]],]


            #3.2 Take the remaining groups as a training data set
            train_data <- datam[-splits[[i]],]   

            model <- randomForest(x=train_data[,-c(target_variable)],
                                y=as.factor(train_data[,c(target_variable)]),
                                ntree=j,mtry=l,keep.forest=TRUE,importance=TRUE)
            yhat<-predict(model,test_data[,-c(target_variable)])
            accuracy_vec[nrow(accuracy_vec)+1,]<-c(i,j,l,F1_Score_micro(as.factor(test_data[,c(target_variable)]),yhat))
            counter<-counter+1
            setTxtProgressBar(pb, counter)
            print(paste("Best F1 Score - ",i, 'fold',j,'trees',l,'mtry',':',accuracy_vec[nrow(accuracy_vec),4],))
            rm('model')
        }
    }
}

#4. Summarize the accuracy of the model using the sample of model evaluation scores
meanF1 <- data.frame(matrix(ncol = 3, nrow = 0))
colnames(meanF1)<-c('n_trees','mtry','mean F1')
for (i in n_trees){
    for (j in m_tries){
            meanF1[nrow(meanF1)+1,]<-c(i,j,mean(filter(accuracy_vec,(n_trees==i & mtry==j))$F1))
    }
}
accuracy_vec
meanF1

  |=                                                                     |   1%[1] "Best F1 Score -  1 fold 10 trees 3 mtry : 0.752542112735505 1"
  |==                                                                    |   2%[1] "Best F1 Score -  1 fold 10 trees 6 mtry : 0.746786385787192 1"
  |==                                                                    |   3%[1] "Best F1 Score -  1 fold 10 trees 12 mtry : 0.731591266643644 1"
  |===                                                                   |   4%[1] "Best F1 Score -  1 fold 20 trees 3 mtry : 0.753808372664134 1"
  |====                                                                  |   6%[1] "Best F1 Score -  1 fold 20 trees 6 mtry : 0.752887456352404 1"
  |=====                                                                 |   7%[1] "Best F1 Score -  1 fold 20 trees 12 mtry : 0.74064694370899 1"
  |=====                                                                 |   8%[1] "Best F1 Score -  1 fold 100 trees 3 mtry : 0.756954836729212 1"
  |======                                                                |   9%[1] "Best F1 Score -  1 fold 100 trees 6 mtry : 0.756686236138291 1"
  |=======                                                               |  10%[1] "Best F1 Score -  1 fold 100 trees 12 mtry : 0.748858447488584 1"
  |========                                                              |  11%[1] "Best F1 Score -  2 fold 10 trees 3 mtry : 0.751083995241932 1"
  |=========                                                             |  12%[1] "Best F1 Score -  2 fold 10 trees 6 mtry : 0.74528989678063 1"
  |=========                                                             |  13%[1] "Best F1 Score -  2 fold 10 trees 12 mtry : 0.734008671961935 1"
  |==========                                                            |  14%[1] "Best F1 Score -  2 fold 20 trees 3 mtry : 0.754268830819999 1"
  |===========                                                           |  16%[1] "Best F1 Score -  2 fold 20 trees 6 mtry : 0.751083995241932 1"
  |============                                                          |  17%[1] "Best F1 Score -  2 fold 20 trees 12 mtry : 0.740992287325889 1"
  |============                                                          |  18%[1] "Best F1 Score -  2 fold 100 trees 3 mtry : 0.757760638501976 1"
  |=============                                                         |  19%[1] "Best F1 Score -  2 fold 100 trees 6 mtry : 0.757108322781167 1"
  |==============                                                        |  20%[1] "Best F1 Score -  2 fold 100 trees 12 mtry : 0.748397989332719 1"
  |===============                                                       |  21%[1] "Best F1 Score -  3 fold 10 trees 3 mtry : 0.752887456352404 1"
  |================                                                      |  22%[1] "Best F1 Score -  3 fold 10 trees 6 mtry : 0.743371321131192 1"
  |================                                                      |  23%[1] "Best F1 Score -  3 fold 10 trees 12 mtry : 0.733049384137217 1"
  |=================                                                     |  24%[1] "Best F1 Score -  3 fold 20 trees 3 mtry : 0.752158397605618 1"
  |==================                                                    |  26%[1] "Best F1 Score -  3 fold 20 trees 6 mtry : 0.746863128813169 1"
  |===================                                                   |  27%[1] "Best F1 Score -  3 fold 20 trees 12 mtry : 0.736310962741261 1"
  |===================                                                   |  28%[1] "Best F1 Score -  3 fold 100 trees 3 mtry : 0.756264149495415 1"
  |====================                                                  |  29%[1] "Best F1 Score -  3 fold 100 trees 6 mtry : 0.753578143586202 1"
  |=====================                                                 |  30%[1] "Best F1 Score -  3 fold 100 trees 12 mtry : 0.743716664748091 1"
  |======================                                                |  31%[1] "Best F1 Score -  4 fold 10 trees 3 mtry : 0.746671271248225 1"
  |=======================                                               |  32%[1] "Best F1 Score -  4 fold 10 trees 6 mtry : 0.739610912858294 1"
  |=======================                                               |  33%[1] "Best F1 Score -  4 fold 10 trees 12 mtry : 0.732243582364453 1"
  |========================                                              |  34%[1] "Best F1 Score -  4 fold 20 trees 3 mtry : 0.751544453397798 1"
  |=========================                                             |  36%[1] "Best F1 Score -  4 fold 20 trees 6 mtry : 0.749242162618472 1"
  |==========================                                            |  37%[1] "Best F1 Score -  4 fold 20 trees 12 mtry : 0.739457426806339 1"
  |==========================                                            |  38%[1] "Best F1 Score -  4 fold 100 trees 3 mtry : 0.756302521008403 1"
  |===========================                                           |  39%[1] "Best F1 Score -  4 fold 100 trees 6 mtry : 0.753194428456314 1"
  |============================                                          |  40%[1] "Best F1 Score -  4 fold 100 trees 12 mtry : 0.744484095007866 1"
  |=============================                                         |  41%[1] "Best F1 Score -  5 fold 10 trees 3 mtry : 0.751966540040674 1"
  |==============================                                        |  42%[1] "Best F1 Score -  5 fold 10 trees 6 mtry : 0.746249184605349 1"
  |==============================                                        |  43%[1] "Best F1 Score -  5 fold 10 trees 12 mtry : 0.737193507540002 1"
  |===============================                                       |  44%[1] "Best F1 Score -  5 fold 20 trees 3 mtry : 0.755535090748628 1"
  |================================                                      |  46%[1] "Best F1 Score -  5 fold 20 trees 6 mtry : 0.753040942404359 1"
  |=================================                                     |  47%[1] "Best F1 Score -  5 fold 20 trees 12 mtry : 0.742603890871417 1"
  |=================================                                     |  48%[1] "Best F1 Score -  5 fold 100 trees 3 mtry : 0.75948735658647 1"
  |==================================                                    |  49%[1] "Best F1 Score -  5 fold 100 trees 6 mtry : 0.758144353631864 1"
  |===================================                                   |  50%[1] "Best F1 Score -  5 fold 100 trees 12 mtry : 0.748513103871686 1"
  |====================================                                  |  51%[1] "Best F1 Score -  6 fold 10 trees 3 mtry : 0.751083995241932 1"
  |=====================================                                 |  52%[1] "Best F1 Score -  6 fold 10 trees 6 mtry : 0.745213153754653 1"
  |=====================================                                 |  53%[1] "Best F1 Score -  6 fold 10 trees 12 mtry : 0.733778442884003 1"
  |======================================                                |  54%[1] "Best F1 Score -  6 fold 20 trees 3 mtry : 0.755151375618741 1"
  |=======================================                               |  56%[1] "Best F1 Score -  6 fold 20 trees 6 mtry : 0.748282874793753 1"
  |========================================                              |  57%[1] "Best F1 Score -  6 fold 20 trees 12 mtry : 0.737730708721845 1"
  |========================================                              |  58%[1] "Best F1 Score -  6 fold 100 trees 3 mtry : 0.757185065807145 1"
  |=========================================                             |  59%[1] "Best F1 Score -  6 fold 100 trees 6 mtry : 0.755535090748628 1"
  |==========================================                            |  60%[1] "Best F1 Score -  6 fold 100 trees 12 mtry : 0.744292237442922 1"
  |===========================================                           |  61%[1] "Best F1 Score -  7 fold 10 trees 3 mtry : 0.75177468247573 1"
  |============================================                          |  62%[1] "Best F1 Score -  7 fold 10 trees 6 mtry : 0.74651778519627 1"
  |============================================                          |  63%[1] "Best F1 Score -  7 fold 10 trees 12 mtry : 0.732435439929396 1"
  |=============================================                         |  64%[1] "Best F1 Score -  7 fold 20 trees 3 mtry : 0.757376923372089 1"
  |==============================================                        |  66%[1] "Best F1 Score -  7 fold 20 trees 6 mtry : 0.75269559878746 1"
  |===============================================                       |  67%[1] "Best F1 Score -  7 fold 20 trees 12 mtry : 0.745136410728675 1"
  |===============================================                       |  68%[1] "Best F1 Score -  7 fold 100 trees 3 mtry : 0.758374582709796 1"
  |================================================                      |  69%[1] "Best F1 Score -  7 fold 100 trees 6 mtry : 0.758489697248762 1"
  |=================================================                     |  70%[1] "Best F1 Score -  7 fold 100 trees 12 mtry : 0.749971221365258 1"
  |==================================================                    |  71%[1] "Best F1 Score -  8 fold 10 trees 3 mtry : 0.751122366754921 1"
  |===================================================                   |  72%[1] "Best F1 Score -  8 fold 10 trees 6 mtry : 0.745251525267641 1"
  |===================================================                   |  73%[1] "Best F1 Score -  8 fold 10 trees 12 mtry : 0.734238901039868 1"
  |====================================================                  |  74%[1] "Best F1 Score -  8 fold 20 trees 3 mtry : 0.76010130079429 1"
  |=====================================================                 |  76%[1] "Best F1 Score -  8 fold 20 trees 6 mtry : 0.750278193469168 1"
  |======================================================                |  77%[1] "Best F1 Score -  8 fold 20 trees 12 mtry : 0.742987606001305 1"
  |======================================================                |  78%[1] "Best F1 Score -  8 fold 100 trees 3 mtry : 0.761098960131998 1"
  |=======================================================               |  79%[1] "Best F1 Score -  8 fold 100 trees 6 mtry : 0.759333870534515 1"
  |========================================================              |  80%[1] "Best F1 Score -  8 fold 100 trees 12 mtry : 0.74993284985227 1"
  |=========================================================             |  81%[1] "Best F1 Score -  9 fold 10 trees 3 mtry : 0.753194428456314 1"
  |==========================================================            |  82%[1] "Best F1 Score -  9 fold 10 trees 6 mtry : 0.746594528222248 1"
  |==========================================================            |  83%[1] "Best F1 Score -  9 fold 10 trees 12 mtry : 0.736848163923103 1"
  |===========================================================           |  84%[1] "Best F1 Score -  9 fold 20 trees 3 mtry : 0.757530409424044 1"
  |============================================================          |  86%[1] "Best F1 Score -  9 fold 20 trees 6 mtry : 0.756033920417482 1"
  |=============================================================         |  87%[1] "Best F1 Score -  9 fold 20 trees 12 mtry : 0.743294578105215 1"
  |=============================================================         |  88%[1] "Best F1 Score -  9 fold 100 trees 3 mtry : 0.759909443229347 1"
  |==============================================================        |  89%[1] "Best F1 Score -  9 fold 100 trees 6 mtry : 0.760254786846245 1"
  |===============================================================       |  90%[1] "Best F1 Score -  9 fold 100 trees 12 mtry : 0.748858447488584 1"
  |================================================================      |  91%[1] "Best F1 Score -  10 fold 10 trees 3 mtry : 0.750460617227084 1"
  |=================================================================     |  92%[1] "Best F1 Score -  10 fold 10 trees 6 mtry : 0.745125134346691 1"
  |=================================================================     |  93%[1] "Best F1 Score -  10 fold 10 trees 12 mtry : 0.73357131890066 1"
  |==================================================================    |  94%[1] "Best F1 Score -  10 fold 20 trees 3 mtry : 0.754721326577614 1"
  |===================================================================   |  96%[1] "Best F1 Score -  10 fold 20 trees 6 mtry : 0.75249500998004 1"
  |====================================================================  |  97%[1] "Best F1 Score -  10 fold 20 trees 12 mtry : 0.74178565945033 1"
  |====================================================================  |  98%[1] "Best F1 Score -  10 fold 100 trees 3 mtry : 0.756986027944112 1"
  |===================================================================== |  99%[1] "Best F1 Score -  10 fold 100 trees 6 mtry : 0.757101182250883 1"
  |======================================================================| 100%[1] "Best F1 Score -  10 fold 100 trees 12 mtry : 0.747850452940273 1"

   fold mean_F1
1   1   0.7489736
2   2   0.7488883
3   3   0.7464666
4   4   0.7458612
5   5   0.7503038
6   6   0.7475837
7   7   0.7503080
8   8   0.7504828
9   9   0.7513910
10 10   0.7488996

In [31]:
meanF1 <- data.frame(matrix(ncol = 3, nrow = 0))
colnames(meanF1)<-c('n_trees','mtry','mean F1')
for (i in n_trees){
    for (j in m_tries){
            meanF1[nrow(meanF1)+1,]<-c(i,j,mean(filter(accuracy_vec,(n_trees==i & mtry==j))$F1))
    }
}
meanF1

  n_trees mtry mean F1
1  10      3   0.7512787
2  10      6   0.7450010
3  10     12   0.7338959
4  20      3   0.7552196
5  20      6   0.7512903
6  20     12   0.7410946
7 100      3   0.7580324
8 100      6   0.7569426
9 100     12   0.7474876

In [3]:
set.seed(2)
k = 10

accuracy_vec <- array(0,k)

n_trees <- c(200,500)
nfeat <- ncol(datam)-1 #I remove 2 to remove building_id and damage_grade
m_tries <- c(floor(0.5*sqrt(nfeat)),floor(sqrt(nfeat)))
accuracy_vec <- data.frame(matrix(ncol = 4, nrow = 0))
colnames(accuracy_vec)<-c('fold','n_trees','mtry','F1')
nrows<-nrow(datam)
datam_idx <- sample(1:nrows)
split <- floor(nrows*0.8)
target_variable <- match('damage_grade', colnames(datam)) #we will remove id.
pb <- txtProgressBar(min = 0, max = length(n_trees), style = 3)

# 1. Shuffle the dataset randomly.
datam_idx <- sample(1:nrow(datam))

# 2. Split the dataset into k groups
max <- ceiling(nrow(datam)/k)
splits <- split(datam_idx, ceiling(seq_along(datam_idx)/max))

pb <- txtProgressBar(min = 0, max = k*length(n_trees)*length(m_tries), style = 3)
counter <-0

# 3. For each unique group:
for (i in 1:k){
    for (j in (n_trees)){
        for (l in m_tries){
            #3.1 Take the group as a hold out or test data set
            test_data <- datam[splits[[i]],]


            #3.2 Take the remaining groups as a training data set
            train_data <- datam[-splits[[i]],]   

            model <- randomForest(x=train_data[,-c(target_variable)],
                                y=as.factor(train_data[,c(target_variable)]),
                                ntree=j,mtry=l,keep.forest=TRUE,importance=TRUE)
            yhat<-predict(model,test_data[,-c(target_variable)])
            accuracy_vec[nrow(accuracy_vec)+1,]<-c(i,j,l,F1_Score_micro(as.factor(test_data[,c(target_variable)]),yhat))
            counter<-counter+1
            setTxtProgressBar(pb, counter)
            print(paste("Best F1 Score - ",i, 'fold',j,'trees',l,'mtry',':',accuracy_vec[nrow(accuracy_vec),4]))
            rm('model')
        }
    }
}

#4. Summarize the accuracy of the model using the sample of model evaluation scores
meanF1 <- data.frame(matrix(ncol = 3, nrow = 0))
colnames(meanF1)<-c('n_trees','mtry','mean F1')
for (i in n_trees){
    for (j in m_tries){
            meanF1[nrow(meanF1)+1,]<-c(i,j,mean(filter(accuracy_vec,(n_trees==i & mtry==j))$F1))
    }
}
accuracy_vec
meanF1

  |==                                                                    |   2%[1] "Best F1 Score -  1 fold 200 trees 3 mtry : 0.757683895475999 1"
  |====                                                                  |   5%[1] "Best F1 Score -  1 fold 200 trees 6 mtry : 0.758681554813706 1"
  |=====                                                                 |   8%[1] "Best F1 Score -  1 fold 500 trees 3 mtry : 0.758950155404628 1"
  |=======                                                               |  10%[1] "Best F1 Score -  1 fold 500 trees 6 mtry : 0.759103641456583 1"
  |=========                                                             |  12%[1] "Best F1 Score -  2 fold 200 trees 3 mtry : 0.75979432869038 1"
  |==========                                                            |  15%[1] "Best F1 Score -  2 fold 200 trees 6 mtry : 0.758374582709796 1"
  |============                                                          |  18%[1] "Best F1 Score -  2 fold 500 trees 3 mtry : 0.760369901385212 1"
  |==============                                                        |  20%[1] "Best F1 Score -  2 fold 500 trees 6 mtry : 0.758835040865661 1"
  |================                                                      |  22%[1] "Best F1 Score -  3 fold 200 trees 3 mtry : 0.756993208242201 1"
  |==================                                                    |  25%[1] "Best F1 Score -  3 fold 200 trees 6 mtry : 0.752964199378381 1"
  |===================                                                   |  28%[1] "Best F1 Score -  3 fold 500 trees 3 mtry : 0.757722266988987 1"
  |=====================                                                 |  30%[1] "Best F1 Score -  3 fold 500 trees 6 mtry : 0.753424657534247 1"
  |=======================                                               |  32%[1] "Best F1 Score -  4 fold 200 trees 3 mtry : 0.754690917462876 1"
  |========================                                              |  35%[1] "Best F1 Score -  4 fold 200 trees 6 mtry : 0.752120026092629 1"
  |==========================                                            |  38%[1] "Best F1 Score -  4 fold 500 trees 3 mtry : 0.755189747131729 1"
  |============================                                          |  40%[1] "Best F1 Score -  4 fold 500 trees 6 mtry : 0.75300257089137 1"
  |==============================                                        |  42%[1] "Best F1 Score -  5 fold 200 trees 3 mtry : 0.76010130079429 1"
  |================================                                      |  45%[1] "Best F1 Score -  5 fold 200 trees 6 mtry : 0.759832700203369 1"
  |=================================                                     |  48%[1] "Best F1 Score -  5 fold 500 trees 3 mtry : 0.759717585664403 1"
  |===================================                                   |  50%[1] "Best F1 Score -  5 fold 500 trees 6 mtry : 0.760523387437167 1"
  |=====================================                                 |  52%[1] "Best F1 Score -  6 fold 200 trees 3 mtry : 0.757415294885077 1"
  |======================================                                |  55%[1] "Best F1 Score -  6 fold 200 trees 6 mtry : 0.758758297839684 1"
  |========================================                              |  58%[1] "Best F1 Score -  6 fold 500 trees 3 mtry : 0.759065269943594 1"
  |==========================================                            |  60%[1] "Best F1 Score -  6 fold 500 trees 6 mtry : 0.757108322781167 1"
  |============================================                          |  62%[1] "Best F1 Score -  7 fold 200 trees 3 mtry : 0.75948735658647 1"
  |==============================================                        |  65%[1] "Best F1 Score -  7 fold 200 trees 6 mtry : 0.758336211196807 1"
  |===============================================                       |  68%[1] "Best F1 Score -  7 fold 500 trees 3 mtry : 0.759525728099459 1"
  |=================================================                     |  70%[1] "Best F1 Score -  7 fold 500 trees 6 mtry : 0.758604811787729 1"
  |===================================================                   |  72%[1] "Best F1 Score -  8 fold 200 trees 3 mtry : 0.762480334599593 1"
  |====================================================                  |  75%[1] "Best F1 Score -  8 fold 200 trees 6 mtry : 0.759372242047504 1"
  |======================================================                |  78%[1] "Best F1 Score -  8 fold 500 trees 3 mtry : 0.762595449138559 1"
  |========================================================              |  80%[1] "Best F1 Score -  8 fold 500 trees 6 mtry : 0.761175703157976 1"
  |==========================================================            |  82%[1] "Best F1 Score -  9 fold 200 trees 3 mtry : 0.760791988028088 1"
  |============================================================          |  85%[1] "Best F1 Score -  9 fold 200 trees 6 mtry : 0.762250105521661 1"
  |=============================================================         |  88%[1] "Best F1 Score -  9 fold 500 trees 3 mtry : 0.761789647365796 1"
  |===============================================================       |  90%[1] "Best F1 Score -  9 fold 500 trees 6 mtry : 0.761175703157976 1"
  |=================================================================     |  92%[1] "Best F1 Score -  10 fold 200 trees 3 mtry : 0.758905266390296 1"
  |==================================================================    |  95%[1] "Best F1 Score -  10 fold 200 trees 6 mtry : 0.756947643175188 1"
  |====================================================================  |  98%[1] "Best F1 Score -  10 fold 500 trees 3 mtry : 0.757638569015815 1"
  |======================================================================| 100%[1] "Best F1 Score -  10 fold 500 trees 6 mtry : 0.756986027944112 1"

  n_trees mtry mean F1
1 200     3    0.7588344
2 200     6    0.7577638
3 500     3    0.7592564
4 500     6    0.7579940